/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SupplyRouteImport } from './routes/supply'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PowerBiReportPageRouteImport } from './routes/power-bi-report-page'
import { Route as PowerBiRouteImport } from './routes/power-bi'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HrRouteImport } from './routes/hr'
import { Route as HistoricalRouteImport } from './routes/historical'
import { Route as FinanceReportRouteImport } from './routes/finance-report'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRoute = SupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerBiReportPageRoute = PowerBiReportPageRouteImport.update({
  id: '/power-bi-report-page',
  path: '/power-bi-report-page',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerBiRoute = PowerBiRouteImport.update({
  id: '/power-bi',
  path: '/power-bi',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalRoute = HistoricalRouteImport.update({
  id: '/historical',
  path: '/historical',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportRoute = FinanceReportRouteImport.update({
  id: '/finance-report',
  path: '/finance-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/benchmarks': typeof BenchmarksRoute
  '/customer': typeof CustomerRoute
  '/finance': typeof FinanceRoute
  '/finance-report': typeof FinanceReportRoute
  '/historical': typeof HistoricalRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/power-bi': typeof PowerBiRoute
  '/power-bi-report-page': typeof PowerBiReportPageRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/supply': typeof SupplyRoute
  '/training': typeof TrainingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/benchmarks': typeof BenchmarksRoute
  '/customer': typeof CustomerRoute
  '/finance': typeof FinanceRoute
  '/finance-report': typeof FinanceReportRoute
  '/historical': typeof HistoricalRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/power-bi': typeof PowerBiRoute
  '/power-bi-report-page': typeof PowerBiReportPageRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/supply': typeof SupplyRoute
  '/training': typeof TrainingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/benchmarks': typeof BenchmarksRoute
  '/customer': typeof CustomerRoute
  '/finance': typeof FinanceRoute
  '/finance-report': typeof FinanceReportRoute
  '/historical': typeof HistoricalRoute
  '/hr': typeof HrRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/power-bi': typeof PowerBiRoute
  '/power-bi-report-page': typeof PowerBiReportPageRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/supply': typeof SupplyRoute
  '/training': typeof TrainingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/benchmarks'
    | '/customer'
    | '/finance'
    | '/finance-report'
    | '/historical'
    | '/hr'
    | '/login'
    | '/onboarding'
    | '/operations'
    | '/power-bi'
    | '/power-bi-report-page'
    | '/profile'
    | '/reconciliation'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/supply'
    | '/training'
    | '/admin/reports'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/benchmarks'
    | '/customer'
    | '/finance'
    | '/finance-report'
    | '/historical'
    | '/hr'
    | '/login'
    | '/onboarding'
    | '/operations'
    | '/power-bi'
    | '/power-bi-report-page'
    | '/profile'
    | '/reconciliation'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/supply'
    | '/training'
    | '/admin/reports'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/benchmarks'
    | '/customer'
    | '/finance'
    | '/finance-report'
    | '/historical'
    | '/hr'
    | '/login'
    | '/onboarding'
    | '/operations'
    | '/power-bi'
    | '/power-bi-report-page'
    | '/profile'
    | '/reconciliation'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/supply'
    | '/training'
    | '/admin/reports'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  BenchmarksRoute: typeof BenchmarksRoute
  CustomerRoute: typeof CustomerRoute
  FinanceRoute: typeof FinanceRoute
  FinanceReportRoute: typeof FinanceReportRoute
  HistoricalRoute: typeof HistoricalRoute
  HrRoute: typeof HrRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OperationsRoute: typeof OperationsRoute
  PowerBiRoute: typeof PowerBiRoute
  PowerBiReportPageRoute: typeof PowerBiReportPageRoute
  ProfileRoute: typeof ProfileRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  SupplyRoute: typeof SupplyRoute
  TrainingRoute: typeof TrainingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply': {
      id: '/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof SupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-bi-report-page': {
      id: '/power-bi-report-page'
      path: '/power-bi-report-page'
      fullPath: '/power-bi-report-page'
      preLoaderRoute: typeof PowerBiReportPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-bi': {
      id: '/power-bi'
      path: '/power-bi'
      fullPath: '/power-bi'
      preLoaderRoute: typeof PowerBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical': {
      id: '/historical'
      path: '/historical'
      fullPath: '/historical'
      preLoaderRoute: typeof HistoricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-report': {
      id: '/finance-report'
      path: '/finance-report'
      fullPath: '/finance-report'
      preLoaderRoute: typeof FinanceReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  BenchmarksRoute: BenchmarksRoute,
  CustomerRoute: CustomerRoute,
  FinanceRoute: FinanceRoute,
  FinanceReportRoute: FinanceReportRoute,
  HistoricalRoute: HistoricalRoute,
  HrRoute: HrRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OperationsRoute: OperationsRoute,
  PowerBiRoute: PowerBiRoute,
  PowerBiReportPageRoute: PowerBiReportPageRoute,
  ProfileRoute: ProfileRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  SupplyRoute: SupplyRoute,
  TrainingRoute: TrainingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
